/*
 * This code is released under the Microsoft Public License (MS-PL). See License.txt, below.
 */
#include "stdafx.h"
#include "struct.h"
#include "get.h"
#include "output.h"
#include "outputIoctlLog.h"

VOID OutputIoctlInfoSense(
	BYTE byKey,
	BYTE byAsc,
	BYTE byAscq
	)
{
	UINT_PTR aSenseKey[][2] = {
		{SCSI_SENSE_NO_SENSE, (UINT_PTR)_T("NO_SENSE")},
		{SCSI_SENSE_RECOVERED_ERROR, (UINT_PTR)_T("RECOVERED_ERROR")}, 
		{SCSI_SENSE_NOT_READY, (UINT_PTR)_T("NOT_READY")}, 
		{SCSI_SENSE_MEDIUM_ERROR, (UINT_PTR)_T("MEDIUM_ERROR")}, 
		{SCSI_SENSE_HARDWARE_ERROR, (UINT_PTR)_T("HARDWARE_ERROR")}, 
		{SCSI_SENSE_ILLEGAL_REQUEST, (UINT_PTR)_T("ILLEGAL_REQUEST")}, 
		{SCSI_SENSE_UNIT_ATTENTION, (UINT_PTR)_T("UNIT_ATTENTION")}, 
		{SCSI_SENSE_DATA_PROTECT, (UINT_PTR)_T("DATA_PROTECT")}, 
		{SCSI_SENSE_BLANK_CHECK, (UINT_PTR)_T("BLANK_CHECK")}, 
		{SCSI_SENSE_UNIQUE, (UINT_PTR)_T("UNIQUE")}, 
		{SCSI_SENSE_COPY_ABORTED, (UINT_PTR)_T("COPY_ABORTED")}, 
		{SCSI_SENSE_ABORTED_COMMAND, (UINT_PTR)_T("ABORTED_COMMAND")}, 
		{SCSI_SENSE_EQUAL, (UINT_PTR)_T("EQUAL")}, 
		{SCSI_SENSE_VOL_OVERFLOW, (UINT_PTR)_T("VOL_OVERFLOW")}, 
		{SCSI_SENSE_MISCOMPARE, (UINT_PTR)_T("MISCOMPARE")} 
	};
	// only C/DVD Device (MMC-6)
	UINT_PTR aSenseAscAscq[][3] = {
		{SCSI_ADSENSE_NO_SENSE, 0x00, (UINT_PTR)_T("NO SENSE")},
		{SCSI_ADSENSE_NO_SEEK_COMPLETE, 0x00, (UINT_PTR)_T("NO SEEK COMPLETE")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_CAUSE_NOT_REPORTABLE, (UINT_PTR)_T("LUN_NOT_READY - CAUSE_NOT_REPORTABLE")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_BECOMING_READY, (UINT_PTR)_T("LUN_NOT_READY - BECOMING_READY")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_INIT_COMMAND_REQUIRED, (UINT_PTR)_T("LUN_NOT_READY - INIT_COMMAND_REQUIRED")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_MANUAL_INTERVENTION_REQUIRED, (UINT_PTR)_T("LUN_NOT_READY - MANUAL_INTERVENTION_REQUIRED")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_FORMAT_IN_PROGRESS, (UINT_PTR)_T("LUN_NOT_READY - FORMAT_IN_PROGRESS")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_OPERATION_IN_PROGRESS, (UINT_PTR)_T("LUN_NOT_READY - OPERATION_IN_PROGRESS")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, SCSI_SENSEQ_LONG_WRITE_IN_PROGRESS, (UINT_PTR)_T("LUN_NOT_READY - LONG_WRITE_IN_PROGRESS")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x09, (UINT_PTR)_T("LUN_NOT_READY - SELF-TEST IN PROGRESS")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x0A, (UINT_PTR)_T("LUN_NOT_READY - ASYMMETRIC ACCESS STATE TRANSITION")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x0B, (UINT_PTR)_T("LUN_NOT_READY - TARGET PORT IN STANDBY STATE")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x0C, (UINT_PTR)_T("LUN_NOT_READY - TARGET PORT IN UNAVAILABLE STATE")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x10, (UINT_PTR)_T("LUN_NOT_READY - AUXILIARY MEMORY NOT ACCESSIBLE")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x11, (UINT_PTR)_T("LUN_NOT_READY - NOTIFY (ENABLE SPINUP) REQUIRED")}, 
		{SCSI_ADSENSE_LUN_NOT_READY, 0x13, (UINT_PTR)_T("LUN_NOT_READY - SA CREATION IN PROGRESS")}, 
		{0x05, 0x00, (UINT_PTR)_T("LOGICAL UNIT DOES NOT RESPOND TO SELECTION")}, 
		{0x06, 0x00, (UINT_PTR)_T("NO REFERENCE POSITION FOUND")}, 
		{0x07, 0x00, (UINT_PTR)_T("MULTIPLE PERIPHERAL DEVICES SELECTED")}, 
		{SCSI_ADSENSE_LUN_COMMUNICATION, SCSI_SENSEQ_COMM_FAILURE, (UINT_PTR)_T("LUN_COMMUNICATION - COMM_FAILURE")}, 
		{SCSI_ADSENSE_LUN_COMMUNICATION, SCSI_SENSEQ_COMM_TIMEOUT, (UINT_PTR)_T("LUN_COMMUNICATION - COMM_TIMEOUT")}, 
		{SCSI_ADSENSE_LUN_COMMUNICATION, SCSI_SENSEQ_COMM_PARITY_ERROR, (UINT_PTR)_T("LUN_COMMUNICATION - COMM_PARITY_ERROR")}, 
		{SCSI_ADSENSE_LUN_COMMUNICATION, SCSI_SESNEQ_COMM_CRC_ERROR, (UINT_PTR)_T("LUN_COMMUNICATION - COMM_CRC_ERROR")}, 
		{SCSI_ADSENSE_LUN_COMMUNICATION, SCSI_SENSEQ_UNREACHABLE_TARGET, (UINT_PTR)_T("LUN_COMMUNICATION - UNREACHABLE_TARGET")}, 
		{0x09, 0x00, (UINT_PTR)_T("TRACK FOLLOWING ERROR")}, 
		{0x09, 0x01, (UINT_PTR)_T("TRACKING SERVO FAILURE")}, 
		{0x09, 0x02, (UINT_PTR)_T("FOCUS SERVO FAILURE")}, 
		{0x09, 0x03, (UINT_PTR)_T("SPINDLE SERVO FAILURE")}, 
		{0x09, 0x04, (UINT_PTR)_T("HEAD SELECT FAULT")}, 
		{0x0A, 0x00, (UINT_PTR)_T("ERROR LOG OVERFLOW")}, 
		{0x0B, 0x00, (UINT_PTR)_T("WARNING")}, 
		{0x0B, 0x01, (UINT_PTR)_T("WARNING - SPECIFIED TEMPERATURE EXCEEDED")}, 
		{0x0B, 0x02, (UINT_PTR)_T("WARNING - ENCLOSURE DEGRADED")}, 
		{0x0B, 0x03, (UINT_PTR)_T("WARNING - BACKGROUND SELF-TEST FAILED")}, 
		{0x0B, 0x04, (UINT_PTR)_T("WARNING - BACKGROUND PRE-SCAN DETECTED MEDIUM ERROR")}, 
		{0x0B, 0x05, (UINT_PTR)_T("WARNING - BACKGROUND MEDIUM SCAN DETECTED MEDIUM ERROR")}, 
		{0x0B, 0x06, (UINT_PTR)_T("WARNING - NON-VOLATILE CACHE NOW VOLATILE")}, 
		{0x0B, 0x07, (UINT_PTR)_T("WARNING - DEGRADED POWER TO NON-VOLATILE CACHE")}, 
		{0x0B, 0x08, (UINT_PTR)_T("WARNING - POWER LOSS EXPECTED")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x00, (UINT_PTR)_T("WRITE ERROR")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x06, (UINT_PTR)_T("BLOCK NOT COMPRESSIBLE")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x07, (UINT_PTR)_T("WRITE ERROR - RECOVERY NEEDED")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x08, (UINT_PTR)_T("WRITE ERROR - RECOVERY FAILED")}, 
		{SCSI_ADSENSE_WRITE_ERROR, SCSI_SENSEQ_LOSS_OF_STREAMING, (UINT_PTR)_T("WRITE ERROR - LOSS OF STREAMING")}, 
		{SCSI_ADSENSE_WRITE_ERROR, SCSI_SENSEQ_PADDING_BLOCKS_ADDED, (UINT_PTR)_T("WRITE ERROR - PADDING BLOCKS ADDED")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x0B, (UINT_PTR)_T("AUXILIARY MEMORY WRITE ERROR")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x0C, (UINT_PTR)_T("WRITE ERROR - UNEXPECTED UNSOLICITED DATA")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x0D, (UINT_PTR)_T("WRITE ERROR - NOT ENOUGH UNSOLICITED DATA")}, 
		{SCSI_ADSENSE_WRITE_ERROR, 0x0F, (UINT_PTR)_T("DEFECTS IN ERROR WINDOW")}, 
		{0x0D, 0x00, (UINT_PTR)_T("ERROR DETECTED BY THIRD PARTY TEMPORARY INITIATOR")}, 
		{0x0D, 0x01, (UINT_PTR)_T("THIRD PARTY DEVICE FAILURE")}, 
		{0x0D, 0x02, (UINT_PTR)_T("COPY TARGET DEVICE NOT REACHABLE")}, 
		{0x0D, 0x03, (UINT_PTR)_T("INCORRECT COPY TARGET DEVICE TYPE")}, 
		{0x0D, 0x04, (UINT_PTR)_T("COPY TARGET DEVICE DATA UNDERRUN")}, 
		{0x0D, 0x05, (UINT_PTR)_T("COPY TARGET DEVICE DATA OVERRUN")}, 
		{0x0E, 0x00, (UINT_PTR)_T("INVALID INFORMATION UNIT")}, 
		{0x0E, 0x01, (UINT_PTR)_T("INFORMATION UNIT TOO SHORT")}, 
		{0x0E, 0x02, (UINT_PTR)_T("INFORMATION UNIT TOO LONG")}, 
		{0x0E, 0x03, (UINT_PTR)_T("INVALID FIELD IN COMMAND INFORMATION UNIT")}, 
		{0x11, 0x00, (UINT_PTR)_T("UNRECOVERED READ ERROR")}, 
		{0x11, 0x01, (UINT_PTR)_T("READ RETRIES EXHAUSTED")}, 
		{0x11, 0x02, (UINT_PTR)_T("ERROR TOO LONG TO CORRECT")}, 
		{0x11, 0x05, (UINT_PTR)_T("L-EC UNCORRECTABLE ERROR")}, 
		{0x11, 0x06, (UINT_PTR)_T("CIRC UNRECOVERED ERROR")}, 
		{0x11, 0x0D, (UINT_PTR)_T("DE-COMPRESSION CRC ERROR")}, 
		{0x11, 0x0E, (UINT_PTR)_T("CANNOT DECOMPRESS USING DECLARED ALGORITHM")}, 
		{0x11, 0x0F, (UINT_PTR)_T("ERROR READING UPC/EAN NUMBER")}, 
		{0x11, 0x10, (UINT_PTR)_T("ERROR READING ISRC NUMBER")}, 
		{0x11, 0x11, (UINT_PTR)_T("READ ERROR - LOSS OF STREAMING")}, 
		{0x11, 0x12, (UINT_PTR)_T("AUXILIARY MEMORY READ ERROR")}, 
		{0x11, 0x13, (UINT_PTR)_T("READ ERROR - FAILED RETRANSMISSION REQUEST")}, 
		{SCSI_ADSENSE_TRACK_ERROR, 0x00, (UINT_PTR)_T("TRACK_ERROR - RECORDED ENTITY NOT FOUND")}, 
		{SCSI_ADSENSE_TRACK_ERROR, 0x01, (UINT_PTR)_T("TRACK_ERROR - RECORD NOT FOUND")}, 
		{SCSI_ADSENSE_SEEK_ERROR, 0x00, (UINT_PTR)_T("SEEK_ERROR - RANDOM POSITIONING ERROR")}, 
		{SCSI_ADSENSE_SEEK_ERROR, 0x01, (UINT_PTR)_T("SEEK_ERROR - MECHANICAL POSITIONING ERROR")}, 
		{SCSI_ADSENSE_SEEK_ERROR, 0x02, (UINT_PTR)_T("SEEK_ERROR - POSITIONING ERROR DETECTED BY READ OF MEDIUM")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x00, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITH NO ERROR CORRECTION APPLIED")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x01, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITH RETRIES")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x02, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITH POSITIVE HEAD OFFSET")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x03, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITH NEGATIVE HEAD OFFSET")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x04, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITH RETRIES AND/OR CIRC APPLIED")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x05, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA USING PREVIOUS SECTOR ID")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x07, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITHOUT ECC - RECOMMEND REASSIGNMENT")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x08, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITHOUT ECC - RECOMMEND REWRITE")}, 
		{SCSI_ADSENSE_REC_DATA_NOECC, 0x09, (UINT_PTR)_T("REC_DATA_NOECC - RECOVERED DATA WITHOUT ECC - DATA REWRITTEN")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x00, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA WITH ERROR CORRECTION APPLIED")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x01, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA WITH ERROR CORR. & RETRIES APPLIED")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x02, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA - DATA AUTO-REALLOCATED")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x03, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA WITH CIRC")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x04, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA WITH L-EC")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x05, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA - RECOMMEND REASSIGNMENT")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x06, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA - RECOMMEND REWRITE")}, 
		{SCSI_ADSENSE_REC_DATA_ECC, 0x08, (UINT_PTR)_T("REC_DATA_ECC - RECOVERED DATA WITH LINKING")}, 
		{SCSI_ADSENSE_PARAMETER_LIST_LENGTH, 0x00, (UINT_PTR)_T("PARAMETER LIST LENGTH ERROR")}, 
		{0x1B, 0x00, (UINT_PTR)_T("SYNCHRONOUS DATA TRANSFER ERROR")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x00, (UINT_PTR)_T("INVALID COMMAND OPERATION CODE")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x01, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - INITIATOR PENDING-ENROLLED")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x02, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - NO ACCESS RIGHTS")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x03, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - INVALID MGMT ID KEY")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x08, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - ENROLLMENT CONFLICT")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x09, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - INVALID LU IDENTIFIER")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x0A, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - INVALID PROXY TOKEN")}, 
		{SCSI_ADSENSE_ILLEGAL_COMMAND, 0x0B, (UINT_PTR)_T("ILLEGAL_COMMAND - ACCESS DENIED - ACL LUN CONFLICT")}, 
		{SCSI_ADSENSE_ILLEGAL_BLOCK, 0x00, (UINT_PTR)_T("LOGICAL BLOCK ADDRESS OUT OF RANGE")}, 
		{SCSI_ADSENSE_ILLEGAL_BLOCK, SCSI_SENSEQ_ILLEGAL_ELEMENT_ADDR, (UINT_PTR)_T("ILLEGAL_BLOCK - MISCOMPARE DURING VERIFY OPERATION")}, 
		{SCSI_ADSENSE_ILLEGAL_BLOCK, 0x02, (UINT_PTR)_T("ILLEGAL_BLOCK - INVALID ADDRESS FOR WRITE")}, 
		{SCSI_ADSENSE_ILLEGAL_BLOCK, 0x03, (UINT_PTR)_T("ILLEGAL_BLOCK - INVALID WRITE CROSSING LAYER JUMP")}, 
		{0x23, 0x00, (UINT_PTR)_T("INVALID TOKEN OPERATION, CAUSE NOT REPORTABLE")}, 
		{SCSI_ADSENSE_INVALID_CDB, 0x00, (UINT_PTR)_T("INVALID FIELD IN CDB")}, 
		{SCSI_ADSENSE_INVALID_CDB, 0x01, (UINT_PTR)_T("CDB DECRYPTION ERROR")}, 
		{SCSI_ADSENSE_INVALID_CDB, 0x08, (UINT_PTR)_T("INVALID XCDB")}, 
		{SCSI_ADSENSE_INVALID_LUN, 0x00, (UINT_PTR)_T("LOGICAL UNIT NOT SUPPORTED")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x00, (UINT_PTR)_T("INVALID FIELD IN PARAMETER LIST")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x01, (UINT_PTR)_T("PARAMETER NOT SUPPORTED")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x02, (UINT_PTR)_T("PARAMETER VALUE INVALID")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x03, (UINT_PTR)_T("THRESHOLD PARAMETERS NOT SUPPORTED")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x04, (UINT_PTR)_T("INVALID RELEASE OF PERSISTENT RESERVATION")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x05, (UINT_PTR)_T("DATA DECRYPTION ERROR")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x06, (UINT_PTR)_T("TOO MANY TARGET DESCRIPTORS")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x07, (UINT_PTR)_T("UNSUPPORTED SEGMENT DESCRIPTOR TYPE CODE")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x08, (UINT_PTR)_T("TOO MANY SEGMENT DESCRIPTORS")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x09, (UINT_PTR)_T("UNSUPPORTED SEGMENT DESCRIPTOR TYPE CODE")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x0A, (UINT_PTR)_T("UNEXPECTED INEXACT SEGMENT")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x0B, (UINT_PTR)_T("INLINE DATA LENGTH EXCEEDED")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x0C, (UINT_PTR)_T("INVALID OPERATION FOR COPY SOURCE OR DESTINATION")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x0D, (UINT_PTR)_T("COPY SEGMENT GRANULARITY VIOLATION")}, 
		{SCSI_ADSENSE_INVALID_FIELD_PARAMETER_LIST, 0x0E, (UINT_PTR)_T("INVALID PARAMETER WHILE PORT IS ENABLED")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x00, (UINT_PTR)_T("WRITE PROTECTED")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x01, (UINT_PTR)_T("HARDWARE WRITE PROTECTED")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x02, (UINT_PTR)_T("LOGICAL UNIT SOFTWARE WRITE PROTECTED")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x03, (UINT_PTR)_T("ASSOCIATED WRITE PROTECT")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x04, (UINT_PTR)_T("PERSISTENT WRITE PROTECT")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x05, (UINT_PTR)_T("PERMANENT WRITE PROTECT")}, 
		{SCSI_ADSENSE_WRITE_PROTECT, 0x06, (UINT_PTR)_T("CONDITIONAL WRITE PROTECT")}, 
		{SCSI_ADSENSE_MEDIUM_CHANGED, 0x00, (UINT_PTR)_T("NOT READY TO READY CHANGE, MEDIUM MAY HAVE CHANGED")}, 
		{SCSI_ADSENSE_MEDIUM_CHANGED, 0x01, (UINT_PTR)_T("IMPORT OR EXPORT ELEMENT ACCESSED")}, 
		{SCSI_ADSENSE_MEDIUM_CHANGED, 0x02, (UINT_PTR)_T("FORMAT-LAYER MAY HAVE CHANGED")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x00, (UINT_PTR)_T("POWER ON, RESET, OR BUS DEVICE RESET OCCURRED")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x01, (UINT_PTR)_T("POWER ON OCCURRED")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x02, (UINT_PTR)_T("SCSI BUS RESET OCCURRED")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x03, (UINT_PTR)_T("BUS DEVICE RESET FUNCTION OCCURRED")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x04, (UINT_PTR)_T("DEVICE INTERNAL RESET")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x05, (UINT_PTR)_T("TRANSCEIVER MODE CHANGED TO SINGLE-ENDED")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x06, (UINT_PTR)_T("TRANSCEIVER MODE CHANGED TO LVD")}, 
		{SCSI_ADSENSE_BUS_RESET, 0x07, (UINT_PTR)_T("I_T NEXUS LOSS OCCURRED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x00, (UINT_PTR)_T("PARAMETERS CHANGED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x01, (UINT_PTR)_T("MODE PARAMETERS CHANGED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x02, (UINT_PTR)_T("LOG PARAMETERS CHANGED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x03, (UINT_PTR)_T("RESERVATIONS PREEMPTED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x04, (UINT_PTR)_T("RESERVATIONS RELEASED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x05, (UINT_PTR)_T("REGISTRATIONS PREEMPTED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x06, (UINT_PTR)_T("ASYMMETRIC ACCESS STATE CHANGED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x07, (UINT_PTR)_T("IMPLICIT ASYMMETRIC ACCESS STATE TRANSITION FAILED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x08, (UINT_PTR)_T("PRIORITY CHANGED")}, 
		{SCSI_ADSENSE_PARAMETERS_CHANGED, 0x14, (UINT_PTR)_T("SA CREATION CAPABILITIES DATA HAS CHANGED")}, 
		{0x2B, 0x00, (UINT_PTR)_T("COPY CANNOT EXECUTE SINCE HOST CANNOT DISCONNECT")}, 
		{0x2C, 0x00, (UINT_PTR)_T("COMMAND SEQUENCE ERROR")}, 
		{0x2C, 0x03, (UINT_PTR)_T("CURRENT PROGRAM AREA IS NOT EMPTY")}, 
		{0x2C, 0x04, (UINT_PTR)_T("CURRENT PROGRAM AREA IS EMPTY")}, 
		{0x2C, 0x06, (UINT_PTR)_T("PERSISTENT PREVENT CONFLICT")}, 
		{0x2C, 0x07, (UINT_PTR)_T("PREVIOUS BUSY STATUS")}, 
		{0x2C, 0x08, (UINT_PTR)_T("PREVIOUS TASK SET FULL STATUS")}, 
		{0x2C, 0x09, (UINT_PTR)_T("PREVIOUS RESERVATION CONFLICT STATUS")}, 
		{SCSI_ADSENSE_INSUFFICIENT_TIME_FOR_OPERATION, 0x00, (UINT_PTR)_T("INSUFFICIENT TIME FOR OPERATION")}, 
		{0x2F, 0x00, (UINT_PTR)_T("COMMANDS CLEARED BY ANOTHER INITIATOR")}, 
		{0x2F, 0x02, (UINT_PTR)_T("COMMANDS CLEARED BY DEVICE SERVER")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x00, (UINT_PTR)_T("INCOMPATIBLE MEDIUM INSTALLED")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x01, (UINT_PTR)_T("CANNOT READ MEDIUM - UNKNOWN FORMAT")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x02, (UINT_PTR)_T("CANNOT READ MEDIUM - INCOMPATIBLE FORMAT")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x03, (UINT_PTR)_T("CLEANING CARTRIDGE INSTALLED")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x04, (UINT_PTR)_T("CANNOT WRITE MEDIUM - UNKNOWN FORMAT")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x05, (UINT_PTR)_T("CANNOT WRITE MEDIUM - INCOMPATIBLE FORMAT")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x06, (UINT_PTR)_T("CANNOT FORMAT MEDIUM - INCOMPATIBLE MEDIUM")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x07, (UINT_PTR)_T("CLEANING FAILURE")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x08, (UINT_PTR)_T("CANNOT WRITE - APPLICATION CODE MISMATCH")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x09, (UINT_PTR)_T("CURRENT SESSION NOT FIXATED FOR APPEND")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x0A, (UINT_PTR)_T("CLEANING REQUEST REJECTED")}, 
		{SCSI_ADSENSE_INVALID_MEDIA, 0x10, (UINT_PTR)_T("MEDIUM NOT FORMATTED")}, 
		{0x31, 0x00, (UINT_PTR)_T("MEDIUM FORMAT CORRUPTED")}, 
		{0x31, 0x01, (UINT_PTR)_T("FORMAT COMMAND FAILED")}, 
		{0x31, 0x02, (UINT_PTR)_T("ZONED FORMATTING FAILED DUE TO SPARE LINKING")}, 
		{0x34, 0x00, (UINT_PTR)_T("ENCLOSURE FAILURE")}, 
		{0x35, 0x00, (UINT_PTR)_T("ENCLOSURE SERVICES FAILURE")}, 
		{0x35, 0x01, (UINT_PTR)_T("UNSUPPORTED ENCLOSURE FUNCTION")}, 
		{0x35, 0x02, (UINT_PTR)_T("ENCLOSURE SERVICES UNAVAILABLE")}, 
		{0x35, 0x03, (UINT_PTR)_T("ENCLOSURE SERVICES TRANSFER FAILURE")}, 
		{0x35, 0x04, (UINT_PTR)_T("ENCLOSURE SERVICES TRANSFER REFUSED")}, 
		{0x35, 0x05, (UINT_PTR)_T("ENCLOSURE SERVICES CHECKSUM ERROR")}, 
		{0x37, 0x00, (UINT_PTR)_T("ROUNDED PARAMETER")}, 
		{0x39, 0x00, (UINT_PTR)_T("SAVING PARAMETERS NOT SUPPORTED")}, 
		{SCSI_ADSENSE_NO_MEDIA_IN_DEVICE, 0x00, (UINT_PTR)_T("MEDIUM NOT PRESENT")}, 
		{SCSI_ADSENSE_NO_MEDIA_IN_DEVICE, 0x01, (UINT_PTR)_T("MEDIUM NOT PRESENT - TRAY CLOSED")}, 
		{SCSI_ADSENSE_NO_MEDIA_IN_DEVICE, 0x02, (UINT_PTR)_T("MEDIUM NOT PRESENT - TRAY OPEN")}, 
		{SCSI_ADSENSE_NO_MEDIA_IN_DEVICE, 0x03, (UINT_PTR)_T("MEDIUM NOT PRESENT - LOADABLE")}, 
		{SCSI_ADSENSE_NO_MEDIA_IN_DEVICE, 0x04, (UINT_PTR)_T("MEDIUM NOT PRESENT - MEDIUM AUXILIARY MEMORY ACCESSIBLE")}, 
		{SCSI_ADSENSE_POSITION_ERROR, SCSI_SENSEQ_DESTINATION_FULL, (UINT_PTR)_T("MEDIUM DESTINATION ELEMENT FULL")}, 
		{SCSI_ADSENSE_POSITION_ERROR, SCSI_SENSEQ_SOURCE_EMPTY, (UINT_PTR)_T("MEDIUM SOURCE ELEMENT EMPTY")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x0F, (UINT_PTR)_T("END OF MEDIUM REACHED")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x11, (UINT_PTR)_T("MEDIUM MAGAZINE NOT ACCESSIBLE")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x12, (UINT_PTR)_T("MEDIUM MAGAZINE REMOVED")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x13, (UINT_PTR)_T("MEDIUM MAGAZINE INSERTED")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x14, (UINT_PTR)_T("MEDIUM MAGAZINE LOCKED")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x15, (UINT_PTR)_T("MEDIUM MAGAZINE UNLOCKED")}, 
		{SCSI_ADSENSE_POSITION_ERROR, 0x16, (UINT_PTR)_T("MECHANICAL POSITIONING OR CHANGER ERROR")}, 
		{0x3D, 0x00, (UINT_PTR)_T("INVALID BITS IN IDENTIFY MESSAGE")}, 
		{0x3E, 0x00, (UINT_PTR)_T("LOGICAL UNIT HAS NOT SELF-CONFIGURED YET")}, 
		{0x3E, 0x01, (UINT_PTR)_T("LOGICAL UNIT FAILURE")}, 
		{0x3E, 0x02, (UINT_PTR)_T("TIMEOUT ON LOGICAL UNIT")}, 
		{0x3E, 0x03, (UINT_PTR)_T("LOGICAL UNIT FAILED SELF-TEST")}, 
		{0x3E, 0x04, (UINT_PTR)_T("LOGICAL UNIT UNABLE TO UPDATE SELF-TEST LOG")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_TARGET_OPERATING_CONDITIONS_CHANGED, (UINT_PTR)_T("TARGET OPERATING CONDITIONS HAVE CHANGED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_MICROCODE_CHANGED, (UINT_PTR)_T("MICROCODE HAS BEEN CHANGED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_OPERATING_DEFINITION_CHANGED, (UINT_PTR)_T("CHANGED OPERATING DEFINITION")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_INQUIRY_DATA_CHANGED, (UINT_PTR)_T("INQUIRY DATA HAS CHANGED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_COMPONENT_DEVICE_ATTACHED, (UINT_PTR)_T("COMPONENT DEVICE ATTACHED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_DEVICE_IDENTIFIER_CHANGED, (UINT_PTR)_T("DEVICE IDENTIFIER CHANGED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_REDUNDANCY_GROUP_MODIFIED, (UINT_PTR)_T("REDUNDANCY GROUP CREATED OR MODIFIED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_REDUNDANCY_GROUP_DELETED, (UINT_PTR)_T("REDUNDANCY GROUP DELETED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_SPARE_MODIFIED, (UINT_PTR)_T("SPARE CREATED OR MODIFIED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_SPARE_DELETED, (UINT_PTR)_T("SPARE DELETED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_VOLUME_SET_MODIFIED, (UINT_PTR)_T("VOLUME SET CREATED OR MODIFIED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_VOLUME_SET_DELETED, (UINT_PTR)_T("VOLUME SET DELETED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_VOLUME_SET_DEASSIGNED, (UINT_PTR)_T("VOLUME SET DEASSIGNED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_VOLUME_SET_REASSIGNED, (UINT_PTR)_T("VOLUME SET REASSIGNED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_REPORTED_LUNS_DATA_CHANGED, (UINT_PTR)_T("REPORTED LUNS DATA HAS CHANGED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_ECHO_BUFFER_OVERWRITTEN, (UINT_PTR)_T("ECHO lpBuf OVERWRITTEN")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_MEDIUM_LOADABLE, (UINT_PTR)_T("MEDIUM LOADABLE")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, SCSI_SENSEQ_MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE, (UINT_PTR)_T("MEDIUM AUXILIARY MEMORY ACCESSIBLE")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, 0x12, (UINT_PTR)_T("iSCSI IP ADDRESS ADDED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, 0x13, (UINT_PTR)_T("iSCSI IP ADDRESS REMOVED")}, 
		{SCSI_ADSENSE_OPERATING_CONDITIONS_CHANGED, 0x14, (UINT_PTR)_T("iSCSI IP ADDRESS CHANGED")}, 
		{0x43, 0x00, (UINT_PTR)_T("MESSAGE ERROR")}, 
		{0x44, 0x00, (UINT_PTR)_T("INTERNAL TARGET FAILURE")}, 
		{0x45, 0x00, (UINT_PTR)_T("SELECT OR RESELECT FAILURE")}, 
		{0x46, 0x00, (UINT_PTR)_T("UNSUCCESSFUL SOFT RESET")}, 
		{0x47, 0x00, (UINT_PTR)_T("SCSI PARITY ERROR")}, 
		{0x47, 0x01, (UINT_PTR)_T("DATA PHASE CRC ERROR DETECTED")}, 
		{0x47, 0x02, (UINT_PTR)_T("SCSI PARITY ERROR DETECTED DURING ST DATA PHASE")}, 
		{0x47, 0x03, (UINT_PTR)_T("INFORMATION UNIT iuCRC ERROR DETECTED")}, 
		{0x47, 0x04, (UINT_PTR)_T("ASYNCHRONOUS INFORMATION PROTECTION ERROR DETECTED")}, 
		{0x47, 0x05, (UINT_PTR)_T("PROTOCOL SERVICE CRC ERROR")}, 
		{0x47, 0x7F, (UINT_PTR)_T("SOME COMMANDS CLEARED BY ISCSI PROTOCOL EVENT")}, 
		{0x48, 0x00, (UINT_PTR)_T("INITIATOR DETECTED ERROR MESSAGE RECEIVED")}, 
		{0x49, 0x00, (UINT_PTR)_T("INVALID MESSAGE ERROR")}, 
		{0x4A, 0x00, (UINT_PTR)_T("COMMAND PHASE ERROR")}, 
		{0x4B, 0x00, (UINT_PTR)_T("DATA PHASE ERROR")}, 
		{0x4B, 0x01, (UINT_PTR)_T("INVALID TARGET PORT TRANSFER TAG RECEIVED")}, 
		{0x4B, 0x02, (UINT_PTR)_T("TOO MUCH WRITE DATA")}, 
		{0x4B, 0x03, (UINT_PTR)_T("ACK/NAK TIMEOUT")}, 
		{0x4B, 0x04, (UINT_PTR)_T("NAK RECEIVED")}, 
		{0x4B, 0x05, (UINT_PTR)_T("DATA OFFSET ERROR")}, 
		{0x4B, 0x06, (UINT_PTR)_T("INITIATOR RESPONSE TIMEOUT")}, 
		{0x4B, 0x07, (UINT_PTR)_T("CONNECTION LOST")}, 
		{0x4C, 0x00, (UINT_PTR)_T("LOGICAL UNIT FAILED SELF-CONFIGURATION")}, 
		{0x4E, 0x00, (UINT_PTR)_T("OVERLAPPED COMMANDS ATTEMPTED")}, 
		{0x51, 0x00, (UINT_PTR)_T("ERASE FAILURE")}, 
		{0x51, 0x01, (UINT_PTR)_T("ERASE FAILURE - INCOMPLETE ERASE OPERATION DETECTED")}, 
		{0x53, 0x00, (UINT_PTR)_T("MEDIA LOAD OR EJECT FAILED")}, 
		{0x53, 0x02, (UINT_PTR)_T("MEDIUM REMOVAL PREVENTED")}, 
		{0x55, 0x02, (UINT_PTR)_T("INSUFFICIENT RESERVATION RESOURCES")}, 
		{0x55, 0x03, (UINT_PTR)_T("INSUFFICIENT RESOURCES")}, 
		{0x55, 0x04, (UINT_PTR)_T("INSUFFICIENT REGISTRATION RESOURCES")}, 
		{0x55, 0x05, (UINT_PTR)_T("INSUFFICIENT ACCESS CONTROL RESOURCES")}, 
		{0x55, 0x06, (UINT_PTR)_T("AUXILIARY MEMORY OUT OF SPACE")}, 
		{0x55, 0x0B, (UINT_PTR)_T("INSUFFICIENT POWER FOR OPERATION")}, 
		{0x57, 0x00, (UINT_PTR)_T("UNABLE TO RECOVER TABLE-OF-CONTENTS")}, 
		{SCSI_ADSENSE_OPERATOR_REQUEST, SCSI_SENSEQ_STATE_CHANGE_INPUT, (UINT_PTR)_T("OPERATOR REQUEST OR STATE CHANGE INPUT")}, 
		{SCSI_ADSENSE_OPERATOR_REQUEST, SCSI_SENSEQ_MEDIUM_REMOVAL, (UINT_PTR)_T("OPERATOR MEDIUM REMOVAL REQUEST")}, 
		{SCSI_ADSENSE_OPERATOR_REQUEST, SCSI_SENSEQ_WRITE_PROTECT_ENABLE, (UINT_PTR)_T("OPERATOR SELECTED WRITE PROTECT")}, 
		{SCSI_ADSENSE_OPERATOR_REQUEST, SCSI_SENSEQ_WRITE_PROTECT_DISABLE, (UINT_PTR)_T("OPERATOR SELECTED WRITE PERMIT")}, 
		{0x5b, 0x00, (UINT_PTR)_T("LOG EXCEPTION")}, 
		{0x5b, 0x01, (UINT_PTR)_T("THRESHOLD CONDITION MET")}, 
		{0x5b, 0x02, (UINT_PTR)_T("LOG COUNTER AT MAXIMUM")}, 
		{0x5b, 0x03, (UINT_PTR)_T("LOG LIST CODES EXHAUSTED")}, 
		{SCSI_ADSENSE_FAILURE_PREDICTION_THRESHOLD_EXCEEDED, 0x00, (UINT_PTR)_T("FAILURE PREDICTION THRESHOLD EXCEEDED")}, 
		{SCSI_ADSENSE_FAILURE_PREDICTION_THRESHOLD_EXCEEDED, 0x01, (UINT_PTR)_T("MEDIA FAILURE PREDICTION THRESHOLD EXCEEDED")}, 
		{SCSI_ADSENSE_FAILURE_PREDICTION_THRESHOLD_EXCEEDED, 0x02, (UINT_PTR)_T("LOGICAL UNIT FAILURE PREDICTION THRESHOLD EXCEEDED")}, 
		{SCSI_ADSENSE_FAILURE_PREDICTION_THRESHOLD_EXCEEDED, 0x03, (UINT_PTR)_T("SPARE AREA EXHAUSTION PREDICTION THRESHOLD EXCEEDED")}, 
		{SCSI_ADSENSE_FAILURE_PREDICTION_THRESHOLD_EXCEEDED, 0xFF, (UINT_PTR)_T("FAILURE PREDICTION THRESHOLD EXCEEDED (FALSE)")}, 
		{0x5E, 0x00, (UINT_PTR)_T("LOW POWER CONDITION ON")}, 
		{0x5E, 0x01, (UINT_PTR)_T("IDLE CONDITION ACTIVATED BY TIMER")}, 
		{0x5E, 0x02, (UINT_PTR)_T("STANDBY CONDITION ACTIVATED BY TIMER")}, 
		{0x5E, 0x03, (UINT_PTR)_T("IDLE CONDITION ACTIVATED BY COMMAND")}, 
		{0x5E, 0x04, (UINT_PTR)_T("STANDBY CONDITION ACTIVATED BY COMMAND")}, 
		{0x5E, 0x05, (UINT_PTR)_T("IDLE_B CONDITION ACTIVATED BY TIMER")}, 
		{0x5E, 0x06, (UINT_PTR)_T("IDLE_B CONDITION ACTIVATED BY COMMAND")}, 
		{0x5E, 0x07, (UINT_PTR)_T("IDLE_C CONDITION ACTIVATED BY TIMER")}, 
		{0x5E, 0x08, (UINT_PTR)_T("IDLE_C CONDITION ACTIVATED BY COMMAND")}, 
		{0x5E, 0x09, (UINT_PTR)_T("STANDBY_Y CONDITION ACTIVATED BY TIMER")}, 
		{0x5E, 0x0A, (UINT_PTR)_T("STANDBY_Y CONDITION ACTIVATED BY COMMAND")}, 
		{0x63, 0x00, (UINT_PTR)_T("END OF USER AREA ENCOUNTERED ON THIS TRACK")}, 
		{0x63, 0x01, (UINT_PTR)_T("PACKET DOES NOT FIT IN AVAILABLE SPACE")}, 
		{SCSI_ADSENSE_ILLEGAL_MODE_FOR_THIS_TRACK, 0x00, (UINT_PTR)_T("ILLEGAL MODE FOR THIS TRACK")}, 
		{SCSI_ADSENSE_ILLEGAL_MODE_FOR_THIS_TRACK, 0x01, (UINT_PTR)_T("INVALID PACKET SIZE")}, 
		{0x65, 0x00, (UINT_PTR)_T("VOLTAGE FAULT")}, 
		{0x67, 0x0A, (UINT_PTR)_T("SET TARGET PORT GROUPS COMMAND FAILED")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, SCSI_SENSEQ_AUTHENTICATION_FAILURE, (UINT_PTR)_T("COPY PROTECTION KEY EXCHANGE FAILURE - AUTHENTICATION FAILURE")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, SCSI_SENSEQ_KEY_NOT_PRESENT, (UINT_PTR)_T("COPY PROTECTION KEY EXCHANGE FAILURE - KEY NOT PRESENT")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, SCSI_SENSEQ_KEY_NOT_ESTABLISHED, (UINT_PTR)_T("COPY PROTECTION KEY EXCHANGE FAILURE - KEY NOT ESTABLISHED")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, SCSI_SENSEQ_READ_OF_SCRAMBLED_SECTOR_WITHOUT_AUTHENTICATION, (UINT_PTR)_T("READ OF SCRAMBLED SECTOR WITHOUT AUTHENTICATION")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, SCSI_SENSEQ_MEDIA_CODE_MISMATCHED_TO_LOGICAL_UNIT, (UINT_PTR)_T("MEDIA REGION CODE IS MISMATCHED TO LOGICAL UNIT REGION")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, SCSI_SENSEQ_LOGICAL_UNIT_RESET_COUNT_ERROR, (UINT_PTR)_T("DRIVE REGION MUST BE PERMANENT/REGION RESET COUNT ERROR")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, 0x06, (UINT_PTR)_T("INSUFFICIENT BLOCK COUNT FOR BINDING NONCE RECORDING")}, 
		{SCSI_ADSENSE_COPY_PROTECTION_FAILURE, 0x07, (UINT_PTR)_T("CONFLICT IN BINDING NONCE RECORDING")}, 
		{0x72, 0x00, (UINT_PTR)_T("SESSION FIXATION ERROR")}, 
		{0x72, 0x01, (UINT_PTR)_T("SESSION FIXATION ERROR WRITING LEAD-IN")}, 
		{0x72, 0x02, (UINT_PTR)_T("SESSION FIXATION ERROR WRITING LEAD-OUT")}, 
		{0x72, 0x03, (UINT_PTR)_T("SESSION FIXATION ERROR - INCOMPLETE TRACK IN SESSION")}, 
		{0x72, 0x04, (UINT_PTR)_T("EMPTY OR PARTIALLY WRITTEN RESERVED TRACK")}, 
		{0x72, 0x05, (UINT_PTR)_T("NO MORE TRACK RESERVATIONS ALLOWED")}, 
		{0x72, 0x06, (UINT_PTR)_T("RMZ EXTENSION IS NOT ALLOWED")}, 
		{0x72, 0x07, (UINT_PTR)_T("NO MORE TEST ZONE EXTENSIONS ARE ALLOWED")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, 0x00, (UINT_PTR)_T("VOLTAGE FAULT")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, SCSI_SENSEQ_POWER_CALIBRATION_AREA_ALMOST_FULL, (UINT_PTR)_T("CD CONTROL ERROR")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, SCSI_SENSEQ_POWER_CALIBRATION_AREA_FULL, (UINT_PTR)_T("POWER CALIBRATION AREA ALMOST FULL")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, SCSI_SENSEQ_POWER_CALIBRATION_AREA_ERROR, (UINT_PTR)_T("POWER CALIBRATION AREA IS FULL")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, SCSI_SENSEQ_PMA_RMA_UPDATE_FAILURE, (UINT_PTR)_T("POWER CALIBRATION AREA ERROR")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, SCSI_SENSEQ_PMA_RMA_IS_FULL, (UINT_PTR)_T("PROGRAM MEMORY AREA UPDATE FAILURE")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, SCSI_SENSEQ_PMA_RMA_ALMOST_FULL, (UINT_PTR)_T("RMA/PMA IS ALMOST FULL")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, 0x10, (UINT_PTR)_T("CURRENT POWER CALIBRATION AREA ALMOST FULL")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, 0x11, (UINT_PTR)_T("CURRENT POWER CALIBRATION AREA IS FULL")}, 
		{SCSI_ADSENSE_POWER_CALIBRATION_ERROR, 0x17, (UINT_PTR)_T("RDZ IS FULL")}, 
		{0x74, 0x08, (UINT_PTR)_T("DIGITAL SIGNATURE VALIDATION FAILURE")}, 
		{0x74, 0x0C, (UINT_PTR)_T("UNABLE TO DECRYPT PARAMETER LIST")}, 
		{0x74, 0x10, (UINT_PTR)_T("SA CREATION PARAMETER VALUE INVALID")}, 
		{0x74, 0x11, (UINT_PTR)_T("SA CREATION PARAMETER VALUE REJECTED")}, 
		{0x74, 0x12, (UINT_PTR)_T("INVALID SA USAGE")}, 
		{0x74, 0x30, (UINT_PTR)_T("SA CREATION PARAMETER NOT SUPPORTED")}, 
		{0x74, 0x40, (UINT_PTR)_T("AUTHENTICATION FAILED")}, 
		{0x74, 0x71, (UINT_PTR)_T("LOGICAL UNIT ACCESS NOT AUTHORIZED")} 
	};
	OutputErrorString(
		_T("Sense data, Key:Asc:Ascq:%02x:%02x:%02x"), byKey, byAsc, byAscq);

	for (INT i = 0; i < sizeof(aSenseKey) / sizeof(INT) / 2; i++) {
		if (byKey == aSenseKey[i][0]) {
			OutputErrorString(_T("(%s."), (LPCTSTR)aSenseKey[i][1]);
			break;
		}
	}
	BOOL bRet = FALSE;
	for (INT i = 0; i < sizeof(aSenseAscAscq) / sizeof(INT) / 3 - 1; i++) {
		if (byAsc == aSenseAscAscq[i][0]) {
			do {
				if (byAscq == aSenseAscAscq[i][1]) {
					OutputErrorString(_T(" %s)"), (LPCTSTR)aSenseAscAscq[i][2]);
					bRet = TRUE;
					break;
				}
				else {
					i++;
				}
			} while (aSenseAscAscq[i][1] < aSenseAscAscq[i + 1][1]);
		}
		if (bRet) {
			break;
		}
	}

	if (byAsc >= SCSI_ADSENSE_VENDOR_UNIQUE || byAscq >= 0x80) {
		OutputErrorString(_T(" VENDER UNIQUE ERROR)"));
	}
	OutputErrorString(_T("\n"));
}

VOID OutputIoctlInfoScsiStatus(
	PSCSI_PASS_THROUGH_DIRECT_WITH_BUFFER swb,
	LPBYTE byScsiStatus,
	LPCTSTR pszFuncName,
	LONG lLineNum
	)
{
	UINT_PTR aScsiStatus[][2] = {
		{SCSISTAT_GOOD, (UINT_PTR)_T("GOOD")}, 
		{SCSISTAT_CHECK_CONDITION, (UINT_PTR)_T("CHECK_CONDITION")}, 
		{SCSISTAT_CONDITION_MET, (UINT_PTR)_T("CONDITION_MET")}, 
		{SCSISTAT_BUSY, (UINT_PTR)_T("BUSY")}, 
		{SCSISTAT_INTERMEDIATE, (UINT_PTR)_T("INTERMEDIATE")}, 
		{SCSISTAT_INTERMEDIATE_COND_MET, (UINT_PTR)_T("INTERMEDIATE_COND_MET")}, 
		{SCSISTAT_RESERVATION_CONFLICT, (UINT_PTR)_T("RESERVATION_CONFLICT")}, 
		{SCSISTAT_COMMAND_TERMINATED, (UINT_PTR)_T("COMMAND_TERMINATED")}, 
		{SCSISTAT_QUEUE_FULL, (UINT_PTR)_T("QUEUE_FULL")}
	};
	if (swb->ScsiPassThroughDirect.ScsiStatus >= SCSISTAT_CHECK_CONDITION) {
		BYTE key = (BYTE)(swb->SenseInfoBuffer[2] & 0x0F);
		BYTE ASC = swb->SenseInfoBuffer[12];
		BYTE ASCQ = swb->SenseInfoBuffer[13];
		if (key != SCSI_SENSE_NO_SENSE || ASC != SCSI_ADSENSE_NO_SENSE || ASCQ != 0x00) {
			for (UINT i = 0; i < sizeof(aScsiStatus) / sizeof(UINT) / 2; i++) {
				if (swb->ScsiPassThroughDirect.ScsiStatus == aScsiStatus[i][0]) {
					OutputErrorString(
						_T("\n[F:%s][L:%d] SCSI bus status codes:%02x-%s\n"), 
						pszFuncName, lLineNum, (UINT)aScsiStatus[i][0], (LPCTSTR)aScsiStatus[i][1]);
					OutputIoctlInfoSense(key, ASC, ASCQ);
					break;
				}
			}
		}
		else {
			// for PLEXTOR PX-320A
			*byScsiStatus = SCSISTAT_GOOD;
		}
	}
}

VOID OutputIoctlScsiAddress(
	PDEVICE_DATA pDevData
	)
{
	OutputDriveLog(
		_T("IoctlScsiGetAddress\n")
		_T("\t    Length: %x\n")
		_T("\tPortNumber: %x\n")
		_T("\t    PathId: %x\n")
		_T("\t  TargetId: %x\n")
		_T("\t       Lun: %x\n"),
		pDevData->address.Length,
		pDevData->address.PortNumber,
		pDevData->address.PathId,
		pDevData->address.TargetId,
		pDevData->address.Lun);
}

VOID OutputIoctlStorageAdaptorDescriptor(
	PSTORAGE_ADAPTER_DESCRIPTOR pAdapterDescriptor
	)
{
	OutputDriveLog(
		_T("StorageAdapterDescriptor\n")
		_T("\t              Version: %d\n")
		_T("\t                 Size: %d\n")
		_T("\tMaximumTransferLength: %d (bytes)\n")
		_T("\t MaximumPhysicalPages: %d\n")
		_T("\t        AlignmentMask: %d\n")
		_T("\t       AdapterUsesPio: %s\n")
		_T("\t     AdapterScansDown: %s\n")
		_T("\t      CommandQueueing: %s\n")
		_T("\t  AcceleratedTransfer: %s\n")
		_T("\t              BusType: "),
		pAdapterDescriptor->Version,
		pAdapterDescriptor->Size,
		pAdapterDescriptor->MaximumTransferLength,
		pAdapterDescriptor->MaximumPhysicalPages,
		pAdapterDescriptor->AlignmentMask,
		BOOLEAN_TO_STRING_TRUE_FALSE(pAdapterDescriptor->AdapterUsesPio),
		BOOLEAN_TO_STRING_TRUE_FALSE(pAdapterDescriptor->AdapterScansDown),
		BOOLEAN_TO_STRING_TRUE_FALSE(pAdapterDescriptor->CommandQueueing),
		BOOLEAN_TO_STRING_TRUE_FALSE(pAdapterDescriptor->AcceleratedTransfer));
	switch (pAdapterDescriptor->BusType) {
	case STORAGE_BUS_TYPE::BusTypeUnknown:
		OutputDriveLog(_T("BusTypeUnknown\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeScsi:
		OutputDriveLog(_T("BusTypeScsi\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeAtapi:
		OutputDriveLog(_T("BusTypeAtapi\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeAta:
		OutputDriveLog(_T("BusTypeAta\n"));
		break;
	case STORAGE_BUS_TYPE::BusType1394:
		OutputDriveLog(_T("BusType1394\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeSsa:
		OutputDriveLog(_T("BusTypeSsa\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeFibre:
		OutputDriveLog(_T("BusTypeFibre\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeUsb:
		OutputDriveLog(_T("BusTypeUsb\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeRAID:
		OutputDriveLog(_T("BusTypeRAID\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeiScsi:
		OutputDriveLog(_T("BusTypeiScsi\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeSas:
		OutputDriveLog(_T("BusTypeSas\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeSata:
		OutputDriveLog(_T("BusTypeSata\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeSd:
		OutputDriveLog(_T("BusTypeSd\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeMmc:
		OutputDriveLog(_T("BusTypeMmc\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeVirtual:
		OutputDriveLog(_T("BusTypeVirtual\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeFileBackedVirtual:
		OutputDriveLog(_T("BusTypeFileBackedVirtual\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeMax:
		OutputDriveLog(_T("BusTypeMax\n"));
		break;
	case STORAGE_BUS_TYPE::BusTypeMaxReserved:
		OutputDriveLog(_T("BusTypeMaxReserved\n"));
		break;
	default:
		OutputDriveLog(_T("BusType???\n"));
		break;
	}
	OutputDriveLog(
		_T("\t      BusMajorVersion: %d\n")
		_T("\t      BusMinorVersion: %d\n"),
		pAdapterDescriptor->BusMajorVersion,
		pAdapterDescriptor->BusMinorVersion);
}

VOID OutputIoctlFloppyInfo(
	PDISK_GEOMETRY pGeom
	)
{
	OutputDiscLog(_T("MediaType: "));
	switch (pGeom[0].MediaType) {
	case Unknown:
		OutputDiscLog(_T("Format is unknown\n"));
		break;
	case F5_1Pt2_512:
		OutputDiscLog(_T("5.25, 1.2MB, 512 bytes/sector\n"));
		break;
	case F3_1Pt44_512:
		OutputDiscLog(_T("3.5, 1.44MB, 512 bytes/sector\n"));
		break;
	case F3_2Pt88_512:
		OutputDiscLog(_T("3.5, 2.88MB, 512 bytes/sector\n"));
		break;
	case F3_20Pt8_512:
		OutputDiscLog(_T("3.5, 20.8MB, 512 bytes/sector\n"));
		break;
	case F3_720_512:
		OutputDiscLog(_T("3.5, 720KB, 512 bytes/sector\n"));
		break;
	case F5_360_512:
		OutputDiscLog(_T("5.25, 360KB, 512 bytes/sector\n"));
		break;
	case F5_320_512:
		OutputDiscLog(_T("5.25, 320KB, 512 bytes/sector\n"));
		break;
	case F5_320_1024:
		OutputDiscLog(_T("5.25, 320KB, 1024 bytes/sector\n"));
		break;
	case F5_180_512:
		OutputDiscLog(_T("5.25, 180KB, 512 bytes/sector\n"));
		break;
	case F5_160_512:
		OutputDiscLog(_T("5.25, 160KB, 512 bytes/sector\n"));
		break;
	case RemovableMedia:
		OutputDiscLog(_T("Removable media other than floppy\n"));
		break;
	case FixedMedia:
		OutputDiscLog(_T("Fixed hard disk media\n"));
		break;
	case F3_120M_512:
		OutputDiscLog(_T("3.5, 120M Floppy\n"));
		break;
	case F3_640_512:
		OutputDiscLog(_T("3.5, 640KB, 512 bytes/sector\n"));
		break;
	case F5_640_512:
		OutputDiscLog(_T("5.25, 640KB, 512 bytes/sector\n"));
		break;
	case F5_720_512:
		OutputDiscLog(_T("5.25, 720KB, 512 bytes/sector\n"));
		break;
	case F3_1Pt2_512:
		OutputDiscLog(_T("3.5, 1.2Mb, 512 bytes/sector\n"));
		break;
	case F3_1Pt23_1024:
		OutputDiscLog(_T("3.5, 1.23Mb, 1024 bytes/sector\n"));
		break;
	case F5_1Pt23_1024:
		OutputDiscLog(_T("5.25, 1.23MB, 1024 bytes/sector\n"));
		break;
	case F3_128Mb_512:
		OutputDiscLog(_T("3.5 MO, 128Mb, 512 bytes/sector\n"));
		break;
	case F3_230Mb_512:
		OutputDiscLog(_T("3.5 MO, 230Mb, 512 bytes/sector\n"));
		break;
	case F8_256_128:
		OutputDiscLog(_T("8, 256KB, 128 bytes/sector\n"));
		break;
	case F3_200Mb_512:
		OutputDiscLog(_T("3.5, 200M Floppy (HiFD)\n"));
		break;
	case F3_240M_512:
		OutputDiscLog(_T("3.5, 240Mb Floppy (HiFD)\n"));
		break;
	case F3_32M_512:
		OutputDiscLog(_T("3.5, 32Mb Floppy\n"));
		break;
	default:
		OutputDiscLog(_T("Unknown\n"));
		break;
	}
	OutputDiscLog(
		_T("\t        Cylinders: %d\n")
		_T("\tTracksPerCylinder: %d\n")
		_T("\t  SectorsPerTrack: %d\n"),
		pGeom[0].Cylinders.LowPart,
		pGeom[0].TracksPerCylinder,
		pGeom[0].SectorsPerTrack);
}
